import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:share_plus/share_plus.dart';
import '../../../core/theme/app_theme.dart';
import '../../../core/utils/currency_formatter.dart';
import '../../../core/providers/app_providers.dart';
import '../../../core/database/app_database.dart';
import '../../../core/utils/export_service.dart';

class EodSummaryScreen extends ConsumerStatefulWidget {
  const EodSummaryScreen({super.key});

  @override
  ConsumerState<EodSummaryScreen> createState() => _EodSummaryScreenState();
}

class _EodSummaryScreenState extends ConsumerState<EodSummaryScreen> {
  DateTime _selectedDay = DateTime.now();

  void _sendEodSms(double todaySales, double cashSales, double momoSales,
      double creditSales, double todayExpenses, double netCash, int saleCount) {
    final session = ref.read(authProvider);
    final businessName = session?.businessName ?? 'DUUKA Shop';
    final ownerPhone = session?.phone ?? '256772123456';
    final dayStr =
        '${_selectedDay.day}/${_selectedDay.month}/${_selectedDay.year}';

    final message = '''
📊 DUUKA EOD SUMMARY - $businessName
📅 Date: $dayStr
💰 Gross Sales: ${CurrencyFormatter.format(todaySales)} ($saleCount txns)
💵 Cash: ${CurrencyFormatter.format(cashSales)}
📱 MoMo: ${CurrencyFormatter.format(momoSales)}
⏳ Credit: ${CurrencyFormatter.format(creditSales)}
🔻 Expenses: ${CurrencyFormatter.format(todayExpenses)}
✅ Net Cash: ${CurrencyFormatter.format(netCash)}
Generated by DUUKA POS
''';

    final sms = LocalSmsData(
      id: 'eod_${DateTime.now().millisecondsSinceEpoch}',
      businessId: session?.businessId ?? 'biz_default',
      phone: ownerPhone,
      message: message,
      type: 'eod_summary',
      status: 'sent',
      createdAt: DateTime.now().millisecondsSinceEpoch,
    );
    ref.read(smsProvider.notifier).logSms(sms);

    Share.share(message, subject: 'EOD Daily Report - $businessName ($dayStr)');
  }

  void _exportEodPdf(
      double todaySales,
      double cashSales,
      double momoSales,
      double creditSales,
      double todayExpenses,
      double netCash,
      int saleCount,
      List<LocalSaleData> daySales) async {
    final session = ref.read(authProvider);
    final businessName = session?.businessName ?? 'DUUKA Shop';
    final dayStr =
        '${_selectedDay.year}-${_selectedDay.month.toString().padLeft(2, '0')}-${_selectedDay.day.toString().padLeft(2, '0')}';

    final expenseMap = <String, double>{
      'Operating Expenses': todayExpenses,
    };

    final bytes = await ExportService.generateFinancialReportPdf(
      businessName: businessName,
      period: 'Day: $dayStr',
      fromDate:
          DateTime(_selectedDay.year, _selectedDay.month, _selectedDay.day),
      toDate: DateTime(
          _selectedDay.year, _selectedDay.month, _selectedDay.day, 23, 59, 59),
      grossRevenue: todaySales,
      costOfGoodsSold: 0,
      grossProfit: todaySales,
      operatingExpenses: todayExpenses,
      netProfit: netCash,
      vatCollected: todaySales * 0.18,
      expenseBreakdown: expenseMap,
    );

    await ExportService.shareOrPrintPdf(
      pdfBytes: bytes,
      fileName: 'DUUKA_EOD_Summary_$dayStr',
    );
  }

  @override
  Widget build(BuildContext context) {
    final sales = ref.watch(salesProvider);
    final expenses = ref.watch(expensesProvider);
    final isDark = Theme.of(context).brightness == Brightness.dark;

    final startOfDay =
        DateTime(_selectedDay.year, _selectedDay.month, _selectedDay.day)
            .millisecondsSinceEpoch;
    final endOfDay = DateTime(
            _selectedDay.year, _selectedDay.month, _selectedDay.day, 23, 59, 59)
        .millisecondsSinceEpoch;

    final daySales = sales
        .where((s) =>
            !s.isVoided &&
            s.localTimestamp >= startOfDay &&
            s.localTimestamp <= endOfDay)
        .toList();
    final dayExpensesList = expenses
        .where((e) => e.date >= startOfDay && e.date <= endOfDay)
        .toList();

    final todaySales =
        daySales.fold<double>(0, (sum, s) => sum + s.totalAmount);
    final cashSales = daySales
        .where((s) => s.paymentMethod.toLowerCase() == 'cash')
        .fold<double>(0, (sum, s) => sum + s.totalAmount);
    final momoSales = daySales
        .where((s) =>
            s.paymentMethod.toLowerCase().contains('momo') ||
            s.paymentMethod.toLowerCase().contains('airtel'))
        .fold<double>(0, (sum, s) => sum + s.totalAmount);
    final creditSales = daySales
        .where((s) => s.isCredit)
        .fold<double>(0, (sum, s) => sum + s.totalAmount);

    final todayExpenses =
        dayExpensesList.fold<double>(0, (sum, e) => sum + e.amount);
    final netCash = (cashSales + momoSales) - todayExpenses;

    // Top item sold on this day
    final itemMap = <String, double>{};
    for (final s in daySales) {
      try {
        final items = jsonDecode(s.itemsJson) as List<dynamic>;
        for (final it in items) {
          final n = it['name'] as String? ?? 'Item';
          final q = (it['quantity'] as num?)?.toDouble() ?? 1.0;
          itemMap[n] = (itemMap[n] ?? 0) + q;
        }
      } catch (_) {}
    }
    final topItems = itemMap.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    return Scaffold(
      backgroundColor:
          isDark ? AppColors.darkBackground : const Color(0xFFF8FAFC),
      appBar: AppBar(
        title: const Text('End-of-Day (EOD) Summary'),
        actions: [
          IconButton(
            icon: const Icon(Icons.calendar_month_rounded),
            tooltip: 'Pick Date',
            onPressed: () async {
              final picked = await showDatePicker(
                context: context,
                initialDate: _selectedDay,
                firstDate: DateTime(2024),
                lastDate: DateTime.now(),
              );
              if (picked != null) setState(() => _selectedDay = picked);
            },
          ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          // Header Card
          Container(
            padding: const EdgeInsets.all(18),
            decoration: BoxDecoration(
              gradient: const LinearGradient(
                colors: [Color(0xFF0F766E), Color(0xFF0D9488)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.circular(20),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      'Daily Performance Summary',
                      style: TextStyle(
                          color: Colors.white.withValues(alpha: 0.8),
                          fontSize: 12,
                          fontWeight: FontWeight.w600),
                    ),
                    Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 8, vertical: 3),
                      decoration: BoxDecoration(
                        color: Colors.white24,
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Text(
                        '${_selectedDay.day}/${_selectedDay.month}/${_selectedDay.year}',
                        style: const TextStyle(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                            fontSize: 11),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                const Text('Gross Total Revenue',
                    style: TextStyle(color: Colors.white70, fontSize: 11)),
                Text(
                  CurrencyFormatter.format(todaySales),
                  style: const TextStyle(
                      color: Colors.white,
                      fontSize: 26,
                      fontWeight: FontWeight.w900,
                      letterSpacing: -0.5),
                ),
                const SizedBox(height: 12),
                Row(
                  children: [
                    _buildStatCol('Transactions', '${daySales.length}'),
                    const SizedBox(width: 20),
                    _buildStatCol(
                        'Expenses', CurrencyFormatter.format(todayExpenses)),
                    const SizedBox(width: 20),
                    _buildStatCol(
                        'Net Cash in Till', CurrencyFormatter.format(netCash)),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),

          // Payment Methods Breakdown
          const Text('Payment Methods Breakdown',
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
          const SizedBox(height: 8),
          Row(
            children: [
              Expanded(
                child: _buildMetricTile(
                  icon: Icons.payments_rounded,
                  label: 'Cash in Hand',
                  value: CurrencyFormatter.format(cashSales),
                  color: const Color(0xFF10B981),
                  isDark: isDark,
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: _buildMetricTile(
                  icon: Icons.phone_android_rounded,
                  label: 'MTN/Airtel MoMo',
                  value: CurrencyFormatter.format(momoSales),
                  color: const Color(0xFFF59E0B),
                  isDark: isDark,
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Row(
            children: [
              Expanded(
                child: _buildMetricTile(
                  icon: Icons.schedule_rounded,
                  label: 'Credit / Debt Given',
                  value: CurrencyFormatter.format(creditSales),
                  color: const Color(0xFF8B5CF6),
                  isDark: isDark,
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: _buildMetricTile(
                  icon: Icons.receipt_long_rounded,
                  label: 'Daily Expenses',
                  value: CurrencyFormatter.format(todayExpenses),
                  color: const Color(0xFFEF4444),
                  isDark: isDark,
                ),
              ),
            ],
          ),
          const SizedBox(height: 18),

          // Action Buttons: Send EOD SMS & Export PDF
          Row(
            children: [
              Expanded(
                child: ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.primaryForest,
                    padding: const EdgeInsets.symmetric(vertical: 14),
                  ),
                  icon: const Icon(Icons.sms_rounded,
                      color: Colors.white, size: 18),
                  label: const Text('Send EOD SMS',
                      style: TextStyle(
                          color: Colors.white, fontWeight: FontWeight.bold)),
                  onPressed: () => _sendEodSms(todaySales, cashSales, momoSales,
                      creditSales, todayExpenses, netCash, daySales.length),
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: OutlinedButton.icon(
                  style: OutlinedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 14),
                  ),
                  icon: const Icon(Icons.picture_as_pdf_rounded, size: 18),
                  label: const Text('Share PDF',
                      style: TextStyle(fontWeight: FontWeight.bold)),
                  onPressed: () => _exportEodPdf(
                      todaySales,
                      cashSales,
                      momoSales,
                      creditSales,
                      todayExpenses,
                      netCash,
                      daySales.length,
                      daySales),
                ),
              ),
            ],
          ),
          const SizedBox(height: 20),

          // Top Selling Products Today
          if (topItems.isNotEmpty) ...[
            const Text('Top Selling Items Today',
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
            const SizedBox(height: 8),
            Card(
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(14)),
              child: Padding(
                padding: const EdgeInsets.symmetric(vertical: 8),
                child: Column(
                  children: topItems.take(5).map((e) {
                    final rank = topItems.indexOf(e) + 1;
                    return ListTile(
                      dense: true,
                      leading: CircleAvatar(
                        radius: 14,
                        backgroundColor: rank == 1
                            ? AppColors.accentGold
                            : const Color(0xFFE2E8F0),
                        child: Text('$rank',
                            style: TextStyle(
                                fontSize: 11,
                                fontWeight: FontWeight.bold,
                                color:
                                    rank == 1 ? Colors.white : Colors.black87)),
                      ),
                      title: Text(e.key,
                          style: const TextStyle(
                              fontWeight: FontWeight.bold, fontSize: 13)),
                      trailing: Text('${e.value.toInt()} units sold',
                          style: const TextStyle(
                              color: AppColors.primaryForest,
                              fontWeight: FontWeight.bold)),
                    );
                  }).toList(),
                ),
              ),
            ),
            const SizedBox(height: 20),
          ],

          // Transaction Breakdown
          Text('Sales Breakdown (${daySales.length} transactions)',
              style:
                  const TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
          const SizedBox(height: 8),
          if (daySales.isEmpty)
            Container(
              padding: const EdgeInsets.all(24),
              alignment: Alignment.center,
              child: const Text('No transactions recorded on this date.',
                  style: TextStyle(color: AppColors.textMuted)),
            )
          else
            ...daySales.map((s) {
              final d = DateTime.fromMillisecondsSinceEpoch(s.localTimestamp);
              final timeStr =
                  '${d.hour.toString().padLeft(2, '0')}:${d.minute.toString().padLeft(2, '0')} · ${s.paymentMethod.toUpperCase()}';
              return Card(
                margin: const EdgeInsets.only(bottom: 6),
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(10)),
                child: ListTile(
                  dense: true,
                  title: Text(
                      '${s.saleNumber} — ${s.customerName ?? 'Walk-in'}',
                      style: const TextStyle(
                          fontWeight: FontWeight.bold, fontSize: 12)),
                  subtitle: Text(timeStr,
                      style: const TextStyle(
                          fontSize: 10, color: AppColors.textMuted)),
                  trailing: Text(
                    CurrencyFormatter.format(s.totalAmount),
                    style: TextStyle(
                      fontWeight: FontWeight.w900,
                      fontSize: 12,
                      color: s.isCredit
                          ? const Color(0xFFD97706)
                          : AppColors.primaryForest,
                    ),
                  ),
                ),
              );
            }),
        ],
      ),
    );
  }

  Widget _buildStatCol(String label, String value) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label,
            style: TextStyle(
                color: Colors.white.withValues(alpha: 0.7), fontSize: 10)),
        const SizedBox(height: 2),
        Text(value,
            style: const TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.bold,
                fontSize: 12)),
      ],
    );
  }

  Widget _buildMetricTile({
    required IconData icon,
    required String label,
    required String value,
    required Color color,
    required bool isDark,
  }) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: isDark ? AppColors.darkCard : Colors.white,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(
            color: isDark ? AppColors.darkBorder : const Color(0xFFE2E8F0)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, size: 16, color: color),
              const SizedBox(width: 6),
              Text(label,
                  style: const TextStyle(
                      fontSize: 11,
                      color: AppColors.textMuted,
                      fontWeight: FontWeight.w600)),
            ],
          ),
          const SizedBox(height: 6),
          Text(
            value,
            style: TextStyle(
                fontSize: 14, fontWeight: FontWeight.w900, color: color),
          ),
        ],
      ),
    );
  }
}
